services:
  web:
    build:
      context: .
      dockerfile: docker/build.Dockerfile
    environment:
      - PORT=5000
      - FASTAPI_ENV=production
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5000:5000"
